apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment2-survey-deployment
  labels:
    app: surveyform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surveyform
  template:
    metadata:
      labels:
        app: surveyform
    spec:
      containers:
        - name: hw2-survey645-container2
          image: atheretu/hw2-survey645:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      